services:
  gateway:
    image: nginx
    container_name: gateway
    ports:
      - '443:443'
    volumes:
      - ./reverse-proxy/conf.d/:/etc/nginx/conf.d/
      - './reverse-proxy/ssl/:/etc/nginx/ssl/'
    depends_on:
      - api
      - front
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracky
      MYSQL_USER: tracky
      MYSQL_PASSWORD: p@ss4tracky
    volumes:
        - data:/var/lib/mysql
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
    depends_on:
      - mysql
    env_file:
      - /api/.env.production.local
  front:
    container_name: front
    restart: unless-stopped
    build:
      context: ./front
    depends_on:
      - api
volumes:
    data: