services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracky
      MYSQL_USER: tracky
      MYSQL_PASSWORD: p@ss4tracky
  api:
    build:
      context: ./api
      dockerfile: /Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql